[package]
name = "shell-execution"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sha2 = { version = "0.10", default-features = false }
shell-primitives = { path = "../shell-primitives" }
shell-state = { path = "../shell-state" }

[dev-dependencies]
shell-fixtures = { path = "../shell-fixtures" }
